### PR TITLE
Check maximum number of characters before urlencode

### PR DESCRIPTION
**Pull request by mobinzk**
We need to check the maximum length of the character before encoding the text as the urlencode changes the number of character for special characters. 

For example `foo & bar` will change to `foo%20%26%20bar%20` and as a result the number of characters would increase. The API accepts the number of characters when encoded.

### CODE REVIEW

**Comment by mobinzk** [comment]
@statickidz We still need to do this fix as it's causing length issue, is there any reason you've closed it without merging it?

**Comment by statickidz** [comment]
@mobinzk it was already implemented, check latest commits and 1.2.0 version

**Comment by mobinzk** [comment]
@statickidz I don't think my change has been implemented. The length check needs to happen before urlencode for the text.

**Comment by statickidz** [comment]
Yeah, you are right, bad checked and thanks for submit it!

**Comment by statickidz** [comment]
@mobinzk Yeah, you are right, bad checked and thanks for submit it!

**Pull request merged**
